//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiscordEventBot.Common.Resources {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DiscordEventBot.Common.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Remarks ähnelt.
        /// </summary>
        internal static string txt__word_remarks {
            get {
                return ResourceManager.GetString("txt__word_remarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Displays a detailed explaination of the given command ähnelt.
        /// </summary>
        internal static string txt_cmd_help_help_cmd_sum {
            get {
                return ResourceManager.GetString("txt_cmd_help_help_cmd_sum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die This provides a filtered list of commands. You will only see what you can use. ähnelt.
        /// </summary>
        internal static string txt_cmd_help_help_mod_sum {
            get {
                return ResourceManager.GetString("txt_cmd_help_help_mod_sum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die This provides a filtered list of commands. You will only see what you can use. ähnelt.
        /// </summary>
        internal static string txt_cmd_help_help_rem {
            get {
                return ResourceManager.GetString("txt_cmd_help_help_rem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Displays every command that you can use ähnelt.
        /// </summary>
        internal static string txt_cmd_help_help_sum {
            get {
                return ResourceManager.GetString("txt_cmd_help_help_sum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Stops the bot. ähnelt.
        /// </summary>
        internal static string txt_mod_adm_cmd_exit_sum {
            get {
                return ResourceManager.GetString("txt_mod_adm_cmd_exit_sum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Admin Commands ähnelt.
        /// </summary>
        internal static string txt_mod_adm_name {
            get {
                return ResourceManager.GetString("txt_mod_adm_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Provides administrative commands. ähnelt.
        /// </summary>
        internal static string txt_mod_adm_sum {
            get {
                return ResourceManager.GetString("txt_mod_adm_sum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sets a role that enables any member of it to use the admin commands. ähnelt.
        /// </summary>
        internal static string txt_mod_admset_cmd_setadminrole_sum {
            get {
                return ResourceManager.GetString("txt_mod_admset_cmd_setadminrole_sum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sets the language the bot speaks. ähnelt.
        /// </summary>
        internal static string txt_mod_admset_cmd_setlang_sum {
            get {
                return ResourceManager.GetString("txt_mod_admset_cmd_setlang_sum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die adds a group to an event ähnelt.
        /// </summary>
        internal static string txt_mod_event_cmd_add_group_sum {
            get {
                return ResourceManager.GetString("txt_mod_event_cmd_add-group_sum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die creates an event within this server ähnelt.
        /// </summary>
        internal static string txt_mod_event_cmd_create_sum {
            get {
                return ResourceManager.GetString("txt_mod_event_cmd_create_sum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Creates an event using a template. Every values, except for the start date are pulled from the predefined template. ähnelt.
        /// </summary>
        internal static string txt_mod_event_cmd_createftpl_sum {
            get {
                return ResourceManager.GetString("txt_mod_event_cmd_createftpl_sum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die deletes the given event ähnelt.
        /// </summary>
        internal static string txt_mod_event_cmd_delete_sum {
            get {
                return ResourceManager.GetString("txt_mod_event_cmd_delete_sum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die joins the given event within the given group ähnelt.
        /// </summary>
        internal static string txt_mod_event_cmd_join_group_sum {
            get {
                return ResourceManager.GetString("txt_mod_event_cmd_join-group_sum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die joins the given event ähnelt.
        /// </summary>
        internal static string txt_mod_event_cmd_join_sum {
            get {
                return ResourceManager.GetString("txt_mod_event_cmd_join_sum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die leaves the given event group ähnelt.
        /// </summary>
        internal static string txt_mod_event_cmd_leave_group_sum {
            get {
                return ResourceManager.GetString("txt_mod_event_cmd_leave-group_sum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die leaves the given event ähnelt.
        /// </summary>
        internal static string txt_mod_event_cmd_leave_sum {
            get {
                return ResourceManager.GetString("txt_mod_event_cmd_leave_sum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die shows the next X events ähnelt.
        /// </summary>
        internal static string txt_mod_event_cmd_show_next_sum {
            get {
                return ResourceManager.GetString("txt_mod_event_cmd_show-next_sum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die View details about the given event ähnelt.
        /// </summary>
        internal static string txt_mod_event_cmd_show_sum {
            get {
                return ResourceManager.GetString("txt_mod_event_cmd_show_sum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Event Commands ähnelt.
        /// </summary>
        internal static string txt_mod_event_name {
            get {
                return ResourceManager.GetString("txt_mod_event_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die provides commands for managing guild events ähnelt.
        /// </summary>
        internal static string txt_mod_event_sum {
            get {
                return ResourceManager.GetString("txt_mod_event_sum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die adds a group to an event template. ähnelt.
        /// </summary>
        internal static string txt_mod_eventtpl_cmd_add_group_sum {
            get {
                return ResourceManager.GetString("txt_mod_eventtpl_cmd_add-group_sum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Creates an event template that can be used to create individual events. ähnelt.
        /// </summary>
        internal static string txt_mod_eventtpl_cmd_create_sum {
            get {
                return ResourceManager.GetString("txt_mod_eventtpl_cmd_create_sum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die This does not delete any events that were created using this template. You need to delete them manually. ähnelt.
        /// </summary>
        internal static string txt_mod_eventtpl_cmd_delete_rem {
            get {
                return ResourceManager.GetString("txt_mod_eventtpl_cmd_delete_rem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Deletes a template ähnelt.
        /// </summary>
        internal static string txt_mod_eventtpl_cmd_delete_sum {
            get {
                return ResourceManager.GetString("txt_mod_eventtpl_cmd_delete_sum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Lists every template in this guild ähnelt.
        /// </summary>
        internal static string txt_mod_eventtpl_cmd_list_sum {
            get {
                return ResourceManager.GetString("txt_mod_eventtpl_cmd_list_sum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Help Commands ähnelt.
        /// </summary>
        internal static string txt_mod_help_name {
            get {
                return ResourceManager.GetString("txt_mod_help_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die If you reply to a message of a failed command and use this command, you will get the reason why the command from this message failed. ähnelt.
        /// </summary>
        internal static string txt_mod_misc_cmd_why_rem {
            get {
                return ResourceManager.GetString("txt_mod_misc_cmd_why_rem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Get the reason why your last command failed ähnelt.
        /// </summary>
        internal static string txt_mod_misc_cmd_why_sum {
            get {
                return ResourceManager.GetString("txt_mod_misc_cmd_why_sum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Miscellaneous commands ähnelt.
        /// </summary>
        internal static string txt_mod_misc_name {
            get {
                return ResourceManager.GetString("txt_mod_misc_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Commands that do not fit in any other category ähnelt.
        /// </summary>
        internal static string txt_mod_misc_sum {
            get {
                return ResourceManager.GetString("txt_mod_misc_sum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You already joined! ähnelt.
        /// </summary>
        internal static string txt_msg_alreadyoined {
            get {
                return ResourceManager.GetString("txt_msg_alreadyoined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Here is a list of commands that the bot understands. You may want more details on specific commands. Use `help *command*` ähnelt.
        /// </summary>
        internal static string txt_msg_cmdoverview_desc {
            get {
                return ResourceManager.GetString("txt_msg_cmdoverview_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bot command reference ähnelt.
        /// </summary>
        internal static string txt_msg_cmdoverview_title {
            get {
                return ResourceManager.GetString("txt_msg_cmdoverview_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Event succesfully created. See below for details. ähnelt.
        /// </summary>
        internal static string txt_msg_eventcreated {
            get {
                return ResourceManager.GetString("txt_msg_eventcreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die This event group cannot be found. ähnelt.
        /// </summary>
        internal static string txt_msg_eventgroupnotfound {
            get {
                return ResourceManager.GetString("txt_msg_eventgroupnotfound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die To view more details about an event type `event show [id]` ähnelt.
        /// </summary>
        internal static string txt_msg_eventlist_footer {
            get {
                return ResourceManager.GetString("txt_msg_eventlist_footer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Upcomming events ähnelt.
        /// </summary>
        internal static string txt_msg_eventlist_title {
            get {
                return ResourceManager.GetString("txt_msg_eventlist_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Event not found ähnelt.
        /// </summary>
        internal static string txt_msg_eventnotfound {
            get {
                return ResourceManager.GetString("txt_msg_eventnotfound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die This group is already full. Please join another group. ähnelt.
        /// </summary>
        internal static string txt_msg_groupfull {
            get {
                return ResourceManager.GetString("txt_msg_groupfull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You can&apos;t add more than 11 groups to an event. ähnelt.
        /// </summary>
        internal static string txt_msg_groupsfull {
            get {
                return ResourceManager.GetString("txt_msg_groupsfull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No summary :( ähnelt.
        /// </summary>
        internal static string txt_msg_nosummary {
            get {
                return ResourceManager.GetString("txt_msg_nosummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You can&apos;t leave an event you are not attending. ähnelt.
        /// </summary>
        internal static string txt_msg_notjoined {
            get {
                return ResourceManager.GetString("txt_msg_notjoined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die OK! ähnelt.
        /// </summary>
        internal static string txt_msg_ok {
            get {
                return ResourceManager.GetString("txt_msg_ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Shhh! I am not allowed to speak in this channel and you should not message me using this channel. I&apos;ve deleted your message before anyone notices. ähnelt.
        /// </summary>
        internal static string txt_msg_wrong_channel {
            get {
                return ResourceManager.GetString("txt_msg_wrong_channel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Alias ähnelt.
        /// </summary>
        internal static string txt_word_alias {
            get {
                return ResourceManager.GetString("txt_word_alias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Attendee ähnelt.
        /// </summary>
        internal static string txt_word_attendee {
            get {
                return ResourceManager.GetString("txt_word_attendee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Duration ähnelt.
        /// </summary>
        internal static string txt_word_duration {
            get {
                return ResourceManager.GetString("txt_word_duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die End time ähnelt.
        /// </summary>
        internal static string txt_word_endtime {
            get {
                return ResourceManager.GetString("txt_word_endtime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die None ähnelt.
        /// </summary>
        internal static string txt_word_none {
            get {
                return ResourceManager.GetString("txt_word_none", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Start time ähnelt.
        /// </summary>
        internal static string txt_word_starttime {
            get {
                return ResourceManager.GetString("txt_word_starttime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Subject ähnelt.
        /// </summary>
        internal static string txt_word_subject {
            get {
                return ResourceManager.GetString("txt_word_subject", resourceCulture);
            }
        }
    }
}
