//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiscordEventBot.Common.Resources {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DiscordEventBot.Common.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Remarks ähnelt.
        /// </summary>
        public static string txt__word_remarks {
            get {
                return ResourceManager.GetString("txt__word_remarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Displays a detailed explaination of the given command ähnelt.
        /// </summary>
        public static string txt_cmd_help_help_cmd_sum {
            get {
                return ResourceManager.GetString("txt_cmd_help_help_cmd_sum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die This provides a filtered list of commands. You will only see what you can use. ähnelt.
        /// </summary>
        public static string txt_cmd_help_help_mod_sum {
            get {
                return ResourceManager.GetString("txt_cmd_help_help_mod_sum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die This provides a filtered list of commands. You will only see what you can use. ähnelt.
        /// </summary>
        public static string txt_cmd_help_help_rem {
            get {
                return ResourceManager.GetString("txt_cmd_help_help_rem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Displays every command that you can use ähnelt.
        /// </summary>
        public static string txt_cmd_help_help_sum {
            get {
                return ResourceManager.GetString("txt_cmd_help_help_sum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Delay time before the bot initialtes the shutdown. ähnelt.
        /// </summary>
        public static string txt_mod_adm_cmd_exit_param_delay_sum {
            get {
                return ResourceManager.GetString("txt_mod_adm_cmd_exit_param_delay_sum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Stops the bot. ähnelt.
        /// </summary>
        public static string txt_mod_adm_cmd_exit_sum {
            get {
                return ResourceManager.GetString("txt_mod_adm_cmd_exit_sum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Admin Commands ähnelt.
        /// </summary>
        public static string txt_mod_adm_name {
            get {
                return ResourceManager.GetString("txt_mod_adm_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Provides administrative commands. ähnelt.
        /// </summary>
        public static string txt_mod_adm_sum {
            get {
                return ResourceManager.GetString("txt_mod_adm_sum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The role that should be given access to certain commands. ähnelt.
        /// </summary>
        public static string txt_mod_admset_cmd_setadminrole_param_role_sum {
            get {
                return ResourceManager.GetString("txt_mod_admset_cmd_setadminrole_param_role_sum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sets a role that enables any member of it to use the admin commands. ähnelt.
        /// </summary>
        public static string txt_mod_admset_cmd_setadminrole_sum {
            get {
                return ResourceManager.GetString("txt_mod_admset_cmd_setadminrole_sum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The channel in wich the bot reacts to commands. ähnelt.
        /// </summary>
        public static string txt_mod_admset_cmd_setbc_param_channel_sum {
            get {
                return ResourceManager.GetString("txt_mod_admset_cmd_setbc_param_channel_sum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The language the bot should speak. E.g. &quot;de&quot; or &quot;en&quot; ähnelt.
        /// </summary>
        public static string txt_mod_admset_cmd_setlang_param_lang_sum {
            get {
                return ResourceManager.GetString("txt_mod_admset_cmd_setlang_param_lang_sum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sets the language the bot speaks. ähnelt.
        /// </summary>
        public static string txt_mod_admset_cmd_setlang_sum {
            get {
                return ResourceManager.GetString("txt_mod_admset_cmd_setlang_sum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The prefix the bot should react to in addition to a mention ähnelt.
        /// </summary>
        public static string txt_mod_admset_cmd_setprefix_param_prefix_sum {
            get {
                return ResourceManager.GetString("txt_mod_admset_cmd_setprefix_param_prefix_sum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die set a custom command prefix for this guild ähnelt.
        /// </summary>
        public static string txt_mod_admset_cmd_setprefix_sum {
            get {
                return ResourceManager.GetString("txt_mod_admset_cmd_setprefix_sum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die adds a group to an event ähnelt.
        /// </summary>
        public static string txt_mod_event_cmd_add_group_sum {
            get {
                return ResourceManager.GetString("txt_mod_event_cmd_add-group_sum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Capacity of the new group. Limits the number of attendees in this group when set. ähnelt.
        /// </summary>
        public static string txt_mod_event_cmd_addgroup_param_capacity_sum {
            get {
                return ResourceManager.GetString("txt_mod_event_cmd_addgroup_param_capacity_sum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The id of the event to wich the group should be added ähnelt.
        /// </summary>
        public static string txt_mod_event_cmd_addgroup_param_eventid_sum {
            get {
                return ResourceManager.GetString("txt_mod_event_cmd_addgroup_param_eventid_sum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Name of the new group ähnelt.
        /// </summary>
        public static string txt_mod_event_cmd_addgroup_param_groupname_sum {
            get {
                return ResourceManager.GetString("txt_mod_event_cmd_addgroup_param_groupname_sum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die a long and detailed description of your event. This can be as long as you want. ähnelt.
        /// </summary>
        public static string txt_mod_event_cmd_create_param_description_sum {
            get {
                return ResourceManager.GetString("txt_mod_event_cmd_create_param_description_sum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The duration of the event. E.g. 2h30m30s for 2 hours, 30 minutes and 30 seconds. You can leave out any component that you don&apos;t need. If your event is only 30 minutes you can write &quot;30m&quot; ähnelt.
        /// </summary>
        public static string txt_mod_event_cmd_create_param_duration_sum {
            get {
                return ResourceManager.GetString("txt_mod_event_cmd_create_param_duration_sum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Start date and time of the event.E.g. &quot;1.1.2020 13:00&quot; for 1st January of 2020 at 1 PM ähnelt.
        /// </summary>
        public static string txt_mod_event_cmd_create_param_startdate_sum {
            get {
                return ResourceManager.GetString("txt_mod_event_cmd_create_param_startdate_sum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Title of the event. ähnelt.
        /// </summary>
        public static string txt_mod_event_cmd_create_param_subject_sum {
            get {
                return ResourceManager.GetString("txt_mod_event_cmd_create_param_subject_sum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die creates an event within this server ähnelt.
        /// </summary>
        public static string txt_mod_event_cmd_create_sum {
            get {
                return ResourceManager.GetString("txt_mod_event_cmd_create_sum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The duration of the event. E.g. 2h30m30s for 2 hours, 30 minutes and 30 seconds. You can leave out any component that you don&apos;t need. If your event is only 30 minutes you can write &quot;30m&quot; ähnelt.
        /// </summary>
        public static string txt_mod_event_cmd_createftpl_param_startdate_sum {
            get {
                return ResourceManager.GetString("txt_mod_event_cmd_createftpl_param_startdate_sum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The id or name of the template you want to create your event from. ähnelt.
        /// </summary>
        public static string txt_mod_event_cmd_createftpl_param_template_sum {
            get {
                return ResourceManager.GetString("txt_mod_event_cmd_createftpl_param_template_sum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Creates an event using a template. Every values, except for the start date are pulled from the predefined template. ähnelt.
        /// </summary>
        public static string txt_mod_event_cmd_createftpl_sum {
            get {
                return ResourceManager.GetString("txt_mod_event_cmd_createftpl_sum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The id of the event you want to delete ähnelt.
        /// </summary>
        public static string txt_mod_event_cmd_delete_param_eventid_sum {
            get {
                return ResourceManager.GetString("txt_mod_event_cmd_delete_param_eventid_sum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die deletes the given event ähnelt.
        /// </summary>
        public static string txt_mod_event_cmd_delete_sum {
            get {
                return ResourceManager.GetString("txt_mod_event_cmd_delete_sum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die joins the given event within the given group ähnelt.
        /// </summary>
        public static string txt_mod_event_cmd_join_group_sum {
            get {
                return ResourceManager.GetString("txt_mod_event_cmd_join-group_sum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The id of the event you want to join ähnelt.
        /// </summary>
        public static string txt_mod_event_cmd_join_param_eventid_sum {
            get {
                return ResourceManager.GetString("txt_mod_event_cmd_join_param_eventid_sum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The user you want to join the event. You can either mention it or write it&apos;s user- or nickname. ähnelt.
        /// </summary>
        public static string txt_mod_event_cmd_join_param_user_sum {
            get {
                return ResourceManager.GetString("txt_mod_event_cmd_join_param_user_sum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die joins the given event ähnelt.
        /// </summary>
        public static string txt_mod_event_cmd_join_sum {
            get {
                return ResourceManager.GetString("txt_mod_event_cmd_join_sum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The id of the event you want to join ähnelt.
        /// </summary>
        public static string txt_mod_event_cmd_joingroup_param_eventid_sum {
            get {
                return ResourceManager.GetString("txt_mod_event_cmd_joingroup_param_eventid_sum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Name of the group you want to join ähnelt.
        /// </summary>
        public static string txt_mod_event_cmd_joingroup_param_groupname_sum {
            get {
                return ResourceManager.GetString("txt_mod_event_cmd_joingroup_param_groupname_sum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The user you want to join the event. You can either mention it or write it&apos;s user- or nickname. ähnelt.
        /// </summary>
        public static string txt_mod_event_cmd_joingroup_param_user_sum {
            get {
                return ResourceManager.GetString("txt_mod_event_cmd_joingroup_param_user_sum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die leaves the given event group ähnelt.
        /// </summary>
        public static string txt_mod_event_cmd_leave_group_sum {
            get {
                return ResourceManager.GetString("txt_mod_event_cmd_leave-group_sum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The id of the event you want to leave ähnelt.
        /// </summary>
        public static string txt_mod_event_cmd_leave_param_eventid_sum {
            get {
                return ResourceManager.GetString("txt_mod_event_cmd_leave_param_eventid_sum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The user you want to leave the event. You can either mention it or write it&apos;s user- or nickname. ähnelt.
        /// </summary>
        public static string txt_mod_event_cmd_leave_param_user_sum {
            get {
                return ResourceManager.GetString("txt_mod_event_cmd_leave_param_user_sum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die leaves the given event ähnelt.
        /// </summary>
        public static string txt_mod_event_cmd_leave_sum {
            get {
                return ResourceManager.GetString("txt_mod_event_cmd_leave_sum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The id of the event you want to leave ähnelt.
        /// </summary>
        public static string txt_mod_event_cmd_leavegroup_param_eventid_sum {
            get {
                return ResourceManager.GetString("txt_mod_event_cmd_leavegroup_param_eventid_sum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The name of the group you want to leave ähnelt.
        /// </summary>
        public static string txt_mod_event_cmd_leavegroup_param_groupname_sum {
            get {
                return ResourceManager.GetString("txt_mod_event_cmd_leavegroup_param_groupname_sum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The user you want to leave the event. You can either mention it or write it&apos;s user- or nickname. ähnelt.
        /// </summary>
        public static string txt_mod_event_cmd_leavegroup_param_user_sum {
            get {
                return ResourceManager.GetString("txt_mod_event_cmd_leavegroup_param_user_sum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die shows the next X events ähnelt.
        /// </summary>
        public static string txt_mod_event_cmd_show_next_sum {
            get {
                return ResourceManager.GetString("txt_mod_event_cmd_show-next_sum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The id of the event you want to view ähnelt.
        /// </summary>
        public static string txt_mod_event_cmd_show_param_eventid_sum {
            get {
                return ResourceManager.GetString("txt_mod_event_cmd_show_param_eventid_sum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die View details about the given event ähnelt.
        /// </summary>
        public static string txt_mod_event_cmd_show_sum {
            get {
                return ResourceManager.GetString("txt_mod_event_cmd_show_sum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The number of events you want to list. Default is 10. ähnelt.
        /// </summary>
        public static string txt_mod_event_cmd_shownext_param_count_sum {
            get {
                return ResourceManager.GetString("txt_mod_event_cmd_shownext_param_count_sum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Event Commands ähnelt.
        /// </summary>
        public static string txt_mod_event_name {
            get {
                return ResourceManager.GetString("txt_mod_event_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die provides commands for managing guild events ähnelt.
        /// </summary>
        public static string txt_mod_event_sum {
            get {
                return ResourceManager.GetString("txt_mod_event_sum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die adds a group to an event template. ähnelt.
        /// </summary>
        public static string txt_mod_eventtpl_cmd_add_group_sum {
            get {
                return ResourceManager.GetString("txt_mod_eventtpl_cmd_add-group_sum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The maximum capacity of the group ähnelt.
        /// </summary>
        public static string txt_mod_eventtpl_cmd_addgroup_param_capacity_sum {
            get {
                return ResourceManager.GetString("txt_mod_eventtpl_cmd_addgroup_param_capacity_sum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Name of the group you want to add. ähnelt.
        /// </summary>
        public static string txt_mod_eventtpl_cmd_addgroup_param_groupname_sum {
            get {
                return ResourceManager.GetString("txt_mod_eventtpl_cmd_addgroup_param_groupname_sum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The id or name of the template you want to add a group to. ähnelt.
        /// </summary>
        public static string txt_mod_eventtpl_cmd_addgroup_param_template_sum {
            get {
                return ResourceManager.GetString("txt_mod_eventtpl_cmd_addgroup_param_template_sum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Description of the event that this template creates. ähnelt.
        /// </summary>
        public static string txt_mod_eventtpl_cmd_create_param_description_sum {
            get {
                return ResourceManager.GetString("txt_mod_eventtpl_cmd_create_param_description_sum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Duration of the event that this template creates. ähnelt.
        /// </summary>
        public static string txt_mod_eventtpl_cmd_create_param_duration_sum {
            get {
                return ResourceManager.GetString("txt_mod_eventtpl_cmd_create_param_duration_sum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The name of the template you want to create. This cannot be changed after the creation. Choose a name that is easy to remember and easy to type. ähnelt.
        /// </summary>
        public static string txt_mod_eventtpl_cmd_create_param_name_sum {
            get {
                return ResourceManager.GetString("txt_mod_eventtpl_cmd_create_param_name_sum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Title of the event that this template creates. ähnelt.
        /// </summary>
        public static string txt_mod_eventtpl_cmd_create_param_subject_sum {
            get {
                return ResourceManager.GetString("txt_mod_eventtpl_cmd_create_param_subject_sum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Creates an event template that can be used to create individual events. ähnelt.
        /// </summary>
        public static string txt_mod_eventtpl_cmd_create_sum {
            get {
                return ResourceManager.GetString("txt_mod_eventtpl_cmd_create_sum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The id or name of the template you want to delete. ähnelt.
        /// </summary>
        public static string txt_mod_eventtpl_cmd_delete_param_template_sum {
            get {
                return ResourceManager.GetString("txt_mod_eventtpl_cmd_delete_param_template_sum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die This does not delete any events that were created using this template. You need to delete them manually. ähnelt.
        /// </summary>
        public static string txt_mod_eventtpl_cmd_delete_rem {
            get {
                return ResourceManager.GetString("txt_mod_eventtpl_cmd_delete_rem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Deletes a template ähnelt.
        /// </summary>
        public static string txt_mod_eventtpl_cmd_delete_sum {
            get {
                return ResourceManager.GetString("txt_mod_eventtpl_cmd_delete_sum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The index of the group you want to delete. This index is 1-based. To delete the first group secify 1. To delete the second group specify 2 and so on. ähnelt.
        /// </summary>
        public static string txt_mod_eventtpl_cmd_deletegrp_param_groupindex_sum {
            get {
                return ResourceManager.GetString("txt_mod_eventtpl_cmd_deletegrp_param_groupindex_sum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The id or name of the template you want to delete a group from. ähnelt.
        /// </summary>
        public static string txt_mod_eventtpl_cmd_deletegrp_param_template_sum {
            get {
                return ResourceManager.GetString("txt_mod_eventtpl_cmd_deletegrp_param_template_sum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Deleting a group from an event template does not affect already created events ähnelt.
        /// </summary>
        public static string txt_mod_eventtpl_cmd_deletegrp_rem {
            get {
                return ResourceManager.GetString("txt_mod_eventtpl_cmd_deletegrp_rem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die deletes a group from an event template ähnelt.
        /// </summary>
        public static string txt_mod_eventtpl_cmd_deletegrp_sum {
            get {
                return ResourceManager.GetString("txt_mod_eventtpl_cmd_deletegrp_sum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Lists every template in this guild ähnelt.
        /// </summary>
        public static string txt_mod_eventtpl_cmd_list_sum {
            get {
                return ResourceManager.GetString("txt_mod_eventtpl_cmd_list_sum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The new description. Leave empty if you don&apos;t want to change it. ähnelt.
        /// </summary>
        public static string txt_mod_eventtpl_cmd_update_param_description_sum {
            get {
                return ResourceManager.GetString("txt_mod_eventtpl_cmd_update_param_description_sum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The new duration of the event. E.g. 2h30m30s for 2 hours, 30 minutes and 30 seconds. You can leave out any component that you don&apos;t need. If your event is only 30 minutes you can write &quot;30m&quot;. specify &quot;null&quot; if you don&apos;t want to change it. ähnelt.
        /// </summary>
        public static string txt_mod_eventtpl_cmd_update_param_duration_sum {
            get {
                return ResourceManager.GetString("txt_mod_eventtpl_cmd_update_param_duration_sum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The new title. Leave empty if you don&apos;t want to change it. ähnelt.
        /// </summary>
        public static string txt_mod_eventtpl_cmd_update_param_subject_sum {
            get {
                return ResourceManager.GetString("txt_mod_eventtpl_cmd_update_param_subject_sum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The id or name of the template you want to change. ähnelt.
        /// </summary>
        public static string txt_mod_eventtpl_cmd_update_param_template_sum {
            get {
                return ResourceManager.GetString("txt_mod_eventtpl_cmd_update_param_template_sum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The name of the command you want to view. ähnelt.
        /// </summary>
        public static string txt_mod_help_cmd_help_param_command_sum {
            get {
                return ResourceManager.GetString("txt_mod_help_cmd_help_param_command_sum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The name of the module you want to view. ähnelt.
        /// </summary>
        public static string txt_mod_help_cmd_help_param_module_sum {
            get {
                return ResourceManager.GetString("txt_mod_help_cmd_help_param_module_sum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Help Commands ähnelt.
        /// </summary>
        public static string txt_mod_help_name {
            get {
                return ResourceManager.GetString("txt_mod_help_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die If you reply to a message of a failed command and use this command, you will get the reason why the command from this message failed. ähnelt.
        /// </summary>
        public static string txt_mod_misc_cmd_why_rem {
            get {
                return ResourceManager.GetString("txt_mod_misc_cmd_why_rem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Get the reason why your last command failed ähnelt.
        /// </summary>
        public static string txt_mod_misc_cmd_why_sum {
            get {
                return ResourceManager.GetString("txt_mod_misc_cmd_why_sum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Miscellaneous commands ähnelt.
        /// </summary>
        public static string txt_mod_misc_name {
            get {
                return ResourceManager.GetString("txt_mod_misc_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Commands that do not fit in any other category ähnelt.
        /// </summary>
        public static string txt_mod_misc_sum {
            get {
                return ResourceManager.GetString("txt_mod_misc_sum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Time in minutes you will receive a notification before an event starts. ähnelt.
        /// </summary>
        public static string txt_mod_set_cmd_nt_param_notifytime_sum {
            get {
                return ResourceManager.GetString("txt_mod_set_cmd_nt_param_notifytime_sum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sets the time in minutes you wish to receive a notification before an event starts. ähnelt.
        /// </summary>
        public static string txt_mod_set_cmd_nt_sum {
            get {
                return ResourceManager.GetString("txt_mod_set_cmd_nt_sum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die User settings ähnelt.
        /// </summary>
        public static string txt_mod_set_name {
            get {
                return ResourceManager.GetString("txt_mod_set_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Provides commands for the user to change it&apos;s own preferences. ähnelt.
        /// </summary>
        public static string txt_mod_set_sum {
            get {
                return ResourceManager.GetString("txt_mod_set_sum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You already joined! ähnelt.
        /// </summary>
        public static string txt_msg_alreadyoined {
            get {
                return ResourceManager.GetString("txt_msg_alreadyoined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Here you can find a list of commands that the bot understands. You may want to know more details about specific commands. Use `help *command*`. Commands can consist of several words. To execute a command it must be written out in full. E.g. `event create`.
        ///All parameters are separated by a space. If you want to use a space within a parameter enclose the value with quotes (&quot;). Date values are always specified including the time. The format follows the language of the bot. For example, you can use the format [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        public static string txt_msg_cmdoverview_desc {
            get {
                return ResourceManager.GetString("txt_msg_cmdoverview_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bot command reference ähnelt.
        /// </summary>
        public static string txt_msg_cmdoverview_title {
            get {
                return ResourceManager.GetString("txt_msg_cmdoverview_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Event succesfully created. See below for details. ähnelt.
        /// </summary>
        public static string txt_msg_eventcreated {
            get {
                return ResourceManager.GetString("txt_msg_eventcreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die This event group cannot be found. ähnelt.
        /// </summary>
        public static string txt_msg_eventgroupnotfound {
            get {
                return ResourceManager.GetString("txt_msg_eventgroupnotfound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die To view more details about an event type `event show [id]` ähnelt.
        /// </summary>
        public static string txt_msg_eventlist_footer {
            get {
                return ResourceManager.GetString("txt_msg_eventlist_footer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Upcomming events ähnelt.
        /// </summary>
        public static string txt_msg_eventlist_title {
            get {
                return ResourceManager.GetString("txt_msg_eventlist_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Event not found ähnelt.
        /// </summary>
        public static string txt_msg_eventnotfound {
            get {
                return ResourceManager.GetString("txt_msg_eventnotfound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0} from server {1} is starting at {2:t} ähnelt.
        /// </summary>
        public static string txt_msg_eventnotification {
            get {
                return ResourceManager.GetString("txt_msg_eventnotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die This group is already full. Please join another group. ähnelt.
        /// </summary>
        public static string txt_msg_groupfull {
            get {
                return ResourceManager.GetString("txt_msg_groupfull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You can&apos;t add more than 11 groups to an event. ähnelt.
        /// </summary>
        public static string txt_msg_groupsfull {
            get {
                return ResourceManager.GetString("txt_msg_groupsfull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No summary :( ähnelt.
        /// </summary>
        public static string txt_msg_nosummary {
            get {
                return ResourceManager.GetString("txt_msg_nosummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You can&apos;t leave an event you are not attending. ähnelt.
        /// </summary>
        public static string txt_msg_notjoined {
            get {
                return ResourceManager.GetString("txt_msg_notjoined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die OK! ähnelt.
        /// </summary>
        public static string txt_msg_ok {
            get {
                return ResourceManager.GetString("txt_msg_ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die This template already exists. You can modify it using the `event template update` command. ähnelt.
        /// </summary>
        public static string txt_msg_templateexists {
            get {
                return ResourceManager.GetString("txt_msg_templateexists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Shhh! I am not allowed to speak in this channel and you should not message me using this channel. I&apos;ve deleted your message before anyone notices. ähnelt.
        /// </summary>
        public static string txt_msg_wrong_channel {
            get {
                return ResourceManager.GetString("txt_msg_wrong_channel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Is optional? ähnelt.
        /// </summary>
        public static string txt_phrase_isoptional {
            get {
                return ResourceManager.GetString("txt_phrase_isoptional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Alias ähnelt.
        /// </summary>
        public static string txt_word_alias {
            get {
                return ResourceManager.GetString("txt_word_alias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Attendee ähnelt.
        /// </summary>
        public static string txt_word_attendee {
            get {
                return ResourceManager.GetString("txt_word_attendee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Type ähnelt.
        /// </summary>
        public static string txt_word_datatype {
            get {
                return ResourceManager.GetString("txt_word_datatype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Duration ähnelt.
        /// </summary>
        public static string txt_word_duration {
            get {
                return ResourceManager.GetString("txt_word_duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die End time ähnelt.
        /// </summary>
        public static string txt_word_endtime {
            get {
                return ResourceManager.GetString("txt_word_endtime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Name ähnelt.
        /// </summary>
        public static string txt_word_name {
            get {
                return ResourceManager.GetString("txt_word_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No ähnelt.
        /// </summary>
        public static string txt_word_no {
            get {
                return ResourceManager.GetString("txt_word_no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die None ähnelt.
        /// </summary>
        public static string txt_word_none {
            get {
                return ResourceManager.GetString("txt_word_none", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Parameters ähnelt.
        /// </summary>
        public static string txt_word_parameters {
            get {
                return ResourceManager.GetString("txt_word_parameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Start time ähnelt.
        /// </summary>
        public static string txt_word_starttime {
            get {
                return ResourceManager.GetString("txt_word_starttime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Subject ähnelt.
        /// </summary>
        public static string txt_word_subject {
            get {
                return ResourceManager.GetString("txt_word_subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Yes ähnelt.
        /// </summary>
        public static string txt_word_yes {
            get {
                return ResourceManager.GetString("txt_word_yes", resourceCulture);
            }
        }
    }
}
