//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiscordEventBot.Common.Resources {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DiscordEventBot.Common.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Remarks ähnelt.
        /// </summary>
        internal static string txt__word_remarks {
            get {
                return ResourceManager.GetString("txt__word_remarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Displays a detailed explaination of the given command ähnelt.
        /// </summary>
        internal static string txt_cmd_help_help_cmd_sum {
            get {
                return ResourceManager.GetString("txt_cmd_help_help_cmd_sum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die This provides a filtered list of commands. You will only see what you can use. ähnelt.
        /// </summary>
        internal static string txt_cmd_help_help_mod_sum {
            get {
                return ResourceManager.GetString("txt_cmd_help_help_mod_sum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die This provides a filtered list of commands. You will only see what you can use. ähnelt.
        /// </summary>
        internal static string txt_cmd_help_help_rem {
            get {
                return ResourceManager.GetString("txt_cmd_help_help_rem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Displays every command that you can use ähnelt.
        /// </summary>
        internal static string txt_cmd_help_help_sum {
            get {
                return ResourceManager.GetString("txt_cmd_help_help_sum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Event Commands ähnelt.
        /// </summary>
        internal static string txt_mod_event_name {
            get {
                return ResourceManager.GetString("txt_mod_event_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Help Commands ähnelt.
        /// </summary>
        internal static string txt_mod_help_name {
            get {
                return ResourceManager.GetString("txt_mod_help_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You already joined! ähnelt.
        /// </summary>
        internal static string txt_msg_alreadyoined {
            get {
                return ResourceManager.GetString("txt_msg_alreadyoined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Here is a list of commands that the bot understands. You may want more details on specific commands. Use `help *command*` ähnelt.
        /// </summary>
        internal static string txt_msg_cmdoverview_desc {
            get {
                return ResourceManager.GetString("txt_msg_cmdoverview_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bot command reference ähnelt.
        /// </summary>
        internal static string txt_msg_cmdoverview_title {
            get {
                return ResourceManager.GetString("txt_msg_cmdoverview_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Event succesfully created. See below for details. ähnelt.
        /// </summary>
        internal static string txt_msg_eventcreated {
            get {
                return ResourceManager.GetString("txt_msg_eventcreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Event not found ähnelt.
        /// </summary>
        internal static string txt_msg_eventnotfound {
            get {
                return ResourceManager.GetString("txt_msg_eventnotfound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No summary :( ähnelt.
        /// </summary>
        internal static string txt_msg_nosummary {
            get {
                return ResourceManager.GetString("txt_msg_nosummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die OK! ähnelt.
        /// </summary>
        internal static string txt_msg_ok {
            get {
                return ResourceManager.GetString("txt_msg_ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Alias ähnelt.
        /// </summary>
        internal static string txt_word_alias {
            get {
                return ResourceManager.GetString("txt_word_alias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Attendee ähnelt.
        /// </summary>
        internal static string txt_word_attendee {
            get {
                return ResourceManager.GetString("txt_word_attendee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die None ähnelt.
        /// </summary>
        internal static string txt_word_none {
            get {
                return ResourceManager.GetString("txt_word_none", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Start time ähnelt.
        /// </summary>
        internal static string txt_word_starttime {
            get {
                return ResourceManager.GetString("txt_word_starttime", resourceCulture);
            }
        }
    }
}
