// <auto-generated />
using System;
using DiscordEventBot.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DiscordEventBot.Model.Migrations
{
    [DbContext(typeof(EventBotContext))]
    [Migration("20210709225558_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.7");

            modelBuilder.Entity("DiscordEventBot.Model.AttendeeGroup", b =>
                {
                    b.Property<ulong>("GroupID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<ulong?>("EventID")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MaxCapacity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("GroupID");

                    b.HasIndex("EventID");

                    b.ToTable("AttendeeGroup");
                });

            modelBuilder.Entity("DiscordEventBot.Model.Event", b =>
                {
                    b.Property<ulong>("EventID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<ulong?>("CreatorUserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("TEXT");

                    b.Property<ulong?>("GuildId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("Start")
                        .HasColumnType("TEXT");

                    b.Property<string>("Subject")
                        .HasColumnType("TEXT");

                    b.HasKey("EventID");

                    b.HasIndex("CreatorUserId");

                    b.HasIndex("GuildId");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("DiscordEventBot.Model.Guild", b =>
                {
                    b.Property<ulong>("GuildId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.HasKey("GuildId");

                    b.ToTable("Guilds");
                });

            modelBuilder.Entity("DiscordEventBot.Model.User", b =>
                {
                    b.Property<ulong>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<ulong?>("AttendeeGroupGroupID")
                        .HasColumnType("INTEGER");

                    b.Property<ulong?>("EventID")
                        .HasColumnType("INTEGER");

                    b.HasKey("UserId");

                    b.HasIndex("AttendeeGroupGroupID");

                    b.HasIndex("EventID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("DiscordEventBot.Model.AttendeeGroup", b =>
                {
                    b.HasOne("DiscordEventBot.Model.Event", null)
                        .WithMany("Groups")
                        .HasForeignKey("EventID");
                });

            modelBuilder.Entity("DiscordEventBot.Model.Event", b =>
                {
                    b.HasOne("DiscordEventBot.Model.User", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatorUserId");

                    b.HasOne("DiscordEventBot.Model.Guild", "Guild")
                        .WithMany()
                        .HasForeignKey("GuildId");

                    b.Navigation("Creator");

                    b.Navigation("Guild");
                });

            modelBuilder.Entity("DiscordEventBot.Model.User", b =>
                {
                    b.HasOne("DiscordEventBot.Model.AttendeeGroup", null)
                        .WithMany("Attendees")
                        .HasForeignKey("AttendeeGroupGroupID");

                    b.HasOne("DiscordEventBot.Model.Event", null)
                        .WithMany("Attendees")
                        .HasForeignKey("EventID");
                });

            modelBuilder.Entity("DiscordEventBot.Model.AttendeeGroup", b =>
                {
                    b.Navigation("Attendees");
                });

            modelBuilder.Entity("DiscordEventBot.Model.Event", b =>
                {
                    b.Navigation("Attendees");

                    b.Navigation("Groups");
                });
#pragma warning restore 612, 618
        }
    }
}
