name: Release

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
      steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"
