name: Docker

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJSON(github) }}
      run: echo "$GITHUB_CONTEXT"
      
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
      
    - name: Set up QEMU
      id: qemu
      uses: docker/setup-qemu-action@v1
      with:
        image: tonistiigi/binfmt:latest
        platforms: all
      
    - id: repo
      uses: ASzc/change-string-case-action@v1
      with:
        string: ${{ github.repository }}
      
    - run: docker build -t ${{ steps.repo.outputs.lowercase }}:latest-linux-arm64 -f ./DiscordEventBot.Service/Dockerfile --platform linux/arm64 .
